spring:
  r2dbc:
    url: r2dbc:mysql://bdg407.synology.me:13307/hair
    username: bdg407
    password: black967
    pool:
      enabled: true                              # 커넥션 풀 활성화
      max-size: 10                               # 최대 커넥션 수
      initial-size: 2                            # 초기 커넥션 수
  redis:
    host: bdg407.synology.me
    port: 16379

logging:
  level:
    io.r2dbc: DEBUG                              # R2DBC 디버깅 로그 활성화

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      testBreaker:
        baseConfig: default