spring:
  r2dbc:
    url: r2dbc:oracle://localhost/ORCL
    username: C##docker
    password: docker123
    pool:
      enabled: true                              # 커넥션 풀 활성화
      initial-size: 50                           # 초기 커넥션 풀 크기
      max-size: 800                              # 최대 커넥션 풀 크기
      max-idle-time: 5m                          # 유휴 커넥션 유지 시간
      max-create-connection-time: 300ms          # 커넥션 생성 대기 시간
      max-acquire-time: 1s                       # 커넥션 대기 시간
  redis:
    host: bdg407.synology.me                     # 호스트 이름
    port: 16379                                  # 포트 번호

logging:
  level:
    io.r2dbc: DEBUG                              # R2DBC 디버깅 로그 활성화

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      testBreaker:
        baseConfig: default
